<article>
  <header>
    <h1>Fall 2012 - welcome!</h1>
  </header>
  <p>the agenda for week 1 is the following:</p>
  <ul>
    <li>
      about this course (outline, administrivia, assignments, etc)  
    </li>
    <li>
      introductions (me, you)
    </li>
    <li>
      web space (thenet.ca)  
    </li>
    <li>
      some expectations & reminders  
    </li>
    <li>
      today's assignment  
    </li>
  </ul>
</article>